/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;


// 被gameUI 引用
export module ui.game {
export class GameSceneUI extends Laya.Scene {
        constructor() { 
            super() 
            console.log("game sceneUI init")
        
        }
        createChildren(): void {
            super.createChildren();
            this.loadScene("scene/GameScene");
            console.log("gameScene loaded")
        }
    }

    // reg 似乎依赖 GameConfig 中的 reg("script/GameUI.ts",GameUI);
    // 
    REG("ui.game.GameSceneUI",GameSceneUI);
}
