/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameUI from "./script/GameUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;

    // 相关取值在 laya.core.js
    static scaleMode: string = Laya.Stage.SCALE_FULL;
    static screenMode: string = Laya.Stage.SCREEN_NONE;
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="scene/GameScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;



    constructor(){}
    // static init(){
        // var reg: Function = Laya.ClassUtils.regClass;
        // reg("script/GameUI.ts",GameUI);
    // }
}
// GameConfig.init();
